-- MySQL Script generated by MySQL Workbench
-- Fri Jun 12 18:40:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eif209_2001_p02 
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `eif209_2001_p02` ;

-- -----------------------------------------------------
-- Schema eif209_2001_p02
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eif209_2001_p02` DEFAULT CHARACTER SET utf8 ;
USE `eif209_2001_p02` ;

-- -----------------------------------------------------
-- Table `eif209_2001_p02`.`Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p02`.`Products` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p02`.`Products` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(4) NULL,
  `description` VARCHAR(60) NULL,
  PRIMARY KEY (`idProduct`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eif209_2001_p02`.`Clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p02`.`Clients` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p02`.`Clients` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `idCard` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(8) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClient`),
  UNIQUE INDEX `idCard_UNIQUE` (`idCard` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eif209_2001_p02`.`Admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p02`.`Admins` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p02`.`Admins` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `idCard` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idAdmin`),
  UNIQUE INDEX `idCard_UNIQUE` (`idCard` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eif209_2001_p02`.`Clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p02`.`Clients` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p02`.`Clients` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `idCard` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(8) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClient`),
  UNIQUE INDEX `idCard_UNIQUE` (`idCard` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eif209_2001_p02`.`Invoices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p02`.`Invoices` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p02`.`Invoices` (
  `idInvoice` INT NOT NULL AUTO_INCREMENT,
  `idClient` INT NOT NULL,
  `date` TIMESTAMP NULL,
  PRIMARY KEY (`idInvoice`),
  INDEX `fk_Invoices_Client1_idx` (`idClient` ASC) VISIBLE,
  CONSTRAINT `fk_Invoices_Client1`
    FOREIGN KEY (`idClient`)
    REFERENCES `eif209_2001_p02`.`Clients` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eif209_2001_p02`.`Details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p02`.`Details` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p02`.`Details` (
  `idInvoice` INT NOT NULL,
  `idProduct` INT NOT NULL,
  PRIMARY KEY (`idInvoice`, `idProduct`),
  INDEX `fk_Details_Invoices1_idx` (`idInvoice` ASC) VISIBLE,
  INDEX `fk_Details_Products1_idx` (`idProduct` ASC) VISIBLE,
  CONSTRAINT `fk_Details_Invoices1`
    FOREIGN KEY (`idInvoice`)
    REFERENCES `eif209_2001_p02`.`Invoices` (`idInvoice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Details_Products1`
    FOREIGN KEY (`idProduct`)
    REFERENCES `eif209_2001_p02`.`Products` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eif209_2001_p02`.`Ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p02`.`Ingredients` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p02`.`Ingredients` (
  `idIngredient` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(3) NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idIngredient`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eif209_2001_p02`.`Feedbacks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p02`.`Feedbacks` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p02`.`Feedbacks` (
  `idFeedback` INT NOT NULL AUTO_INCREMENT,
  `idClient` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`idFeedback`),
  INDEX `fk_Feedbacks_Client1_idx` (`idClient` ASC) VISIBLE,
  CONSTRAINT `fk_Feedbacks_Client1`
    FOREIGN KEY (`idClient`)
    REFERENCES `eif209_2001_p02`.`Clients` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eif209_2001_p02`.`Recipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p02`.`Recipe` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p02`.`Recipe` (
  `idProduct` INT NOT NULL,
  `idIngredient` INT NOT NULL,
  PRIMARY KEY (`idProduct`, `idIngredient`),
  INDEX `fk_Products_has_Ingredients_Ingredients1_idx` (`idIngredient` ASC) VISIBLE,
  INDEX `fk_Products_has_Ingredients_Products1_idx` (`idProduct` ASC) VISIBLE,
  CONSTRAINT `fk_Products_has_Ingredients_Products1`
    FOREIGN KEY (`idProduct`)
    REFERENCES `eif209_2001_p02`.`Products` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_has_Ingredients_Ingredients1`
    FOREIGN KEY (`idIngredient`)
    REFERENCES `eif209_2001_p02`.`Ingredients` (`idIngredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eif209_2001_p02`.`Size`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p02`.`Size` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p02`.`Size` (
  `idSize` INT NOT NULL AUTO_INCREMENT,
  `size` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSize`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eif209_2001_p02`.`Inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p02`.`Inventory` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p02`.`Inventory` (
  `idProduct` INT NOT NULL,
  `idSize` INT NOT NULL,
  `price` DOUBLE NOT NULL,
  PRIMARY KEY (`idProduct`, `idSize`),
  INDEX `fk_table1_Products1_idx` (`idProduct` ASC) VISIBLE,
  INDEX `fk_ProductSize_Size1_idx` (`idSize` ASC) VISIBLE,
  CONSTRAINT `fk_table1_Products1`
    FOREIGN KEY (`idProduct`)
    REFERENCES `eif209_2001_p02`.`Products` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductSize_Size1`
    FOREIGN KEY (`idSize`)
    REFERENCES `eif209_2001_p02`.`Size` (`idSize`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eif209_2001_p02`.`Status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p02`.`Status` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p02`.`Status` (
  `idStatus` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`idStatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eif209_2001_p02`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p02`.`Order` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p02`.`Order` (
  `idStatus` INT NOT NULL DEFAULT 1,
  `idInvoice` INT NOT NULL,
  PRIMARY KEY (`idStatus`, `idInvoice`),
  INDEX `fk_Status_has_Invoices_Invoices1_idx` (`idInvoice` ASC) VISIBLE,
  INDEX `fk_Status_has_Invoices_Status1_idx` (`idStatus` ASC) VISIBLE,
  CONSTRAINT `fk_Status_has_Invoices_Status1`
    FOREIGN KEY (`idStatus`)
    REFERENCES `eif209_2001_p02`.`Status` (`idStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Status_has_Invoices_Invoices1`
    FOREIGN KEY (`idInvoice`)
    REFERENCES `eif209_2001_p02`.`Invoices` (`idInvoice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `eif209_2001_p02`.`Products`
-- -----------------------------------------------------
START TRANSACTION;
USE `eif209_2001_p02`;
INSERT INTO `eif209_2001_p02`.`Products` (`idProduct`, `code`, `description`) VALUES (DEFAULT, 'PEPP', 'Pizza de Peperronie');
INSERT INTO `eif209_2001_p02`.`Products` (`idProduct`, `code`, `description`) VALUES (DEFAULT, 'JAQP', 'Pizza de Jamón y Queso');
INSERT INTO `eif209_2001_p02`.`Products` (`idProduct`, `code`, `description`) VALUES (DEFAULT, 'SUPP', 'Pizza Suprema');
INSERT INTO `eif209_2001_p02`.`Products` (`idProduct`, `code`, `description`) VALUES (DEFAULT, 'COCA', 'Coca Cola ');
INSERT INTO `eif209_2001_p02`.`Products` (`idProduct`, `code`, `description`) VALUES (DEFAULT, 'FANN', 'Fanta Naranja');
INSERT INTO `eif209_2001_p02`.`Products` (`idProduct`, `code`, `description`) VALUES (DEFAULT, 'PIEA', 'Pie de Arandanos');
INSERT INTO `eif209_2001_p02`.`Products` (`idProduct`, `code`, `description`) VALUES (DEFAULT, 'TREL', 'Tres Leches');

COMMIT;


-- -----------------------------------------------------
-- Data for table `eif209_2001_p02`.`Admins`
-- -----------------------------------------------------
START TRANSACTION;
USE `eif209_2001_p02`;
INSERT INTO `eif209_2001_p02`.`Admins` (`idAdmin`, `idCard`, `name`, `lastname`, `password`) VALUES (DEFAULT, '504250570', 'Erick ', 'Badilla Gonzalez', '1234567b');
INSERT INTO `eif209_2001_p02`.`Admins` (`idAdmin`, `idCard`, `name`, `lastname`, `password`) VALUES (DEFAULT, '504250413', 'Carlos', 'Zhou Zheng', '1234567b');

COMMIT;


-- -----------------------------------------------------
-- Data for table `eif209_2001_p02`.`Clients`
-- -----------------------------------------------------
START TRANSACTION;
USE `eif209_2001_p02`;
INSERT INTO `eif209_2001_p02`.`Clients` (`idClient`, `idCard`, `name`, `lastname`, `address`, `phone`, `password`) VALUES (DEFAULT, '185045679', 'Ignacio', 'Monge Salazar', 'Montes de Oca Uruca', '60405010', 'qwer');
INSERT INTO `eif209_2001_p02`.`Clients` (`idClient`, `idCard`, `name`, `lastname`, `address`, `phone`, `password`) VALUES (DEFAULT, '150305402', 'Nicole ', 'Cannet Porras ', 'San Antonio de Belen ', '50501012', 'qwer');

COMMIT;


-- -----------------------------------------------------
-- Data for table `eif209_2001_p02`.`Invoices`
-- -----------------------------------------------------
START TRANSACTION;
USE `eif209_2001_p02`;
INSERT INTO `eif209_2001_p02`.`Invoices` (`idInvoice`, `idClient`, `date`) VALUES (DEFAULT, 1, NULL);
INSERT INTO `eif209_2001_p02`.`Invoices` (`idInvoice`, `idClient`, `date`) VALUES (DEFAULT, 2, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `eif209_2001_p02`.`Details`
-- -----------------------------------------------------
START TRANSACTION;
USE `eif209_2001_p02`;
INSERT INTO `eif209_2001_p02`.`Details` (`idInvoice`, `idProduct`) VALUES (1, 1);
INSERT INTO `eif209_2001_p02`.`Details` (`idInvoice`, `idProduct`) VALUES (1, 2);
INSERT INTO `eif209_2001_p02`.`Details` (`idInvoice`, `idProduct`) VALUES (1, 3);
INSERT INTO `eif209_2001_p02`.`Details` (`idInvoice`, `idProduct`) VALUES (2, 1);
INSERT INTO `eif209_2001_p02`.`Details` (`idInvoice`, `idProduct`) VALUES (2, 2);
INSERT INTO `eif209_2001_p02`.`Details` (`idInvoice`, `idProduct`) VALUES (2, 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `eif209_2001_p02`.`Ingredients`
-- -----------------------------------------------------
START TRANSACTION;
USE `eif209_2001_p02`;
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'PEP', 'Pepperoni');
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'JAP', 'Jamón de Pollo');
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'QUM', 'Queso Mozzarella');
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'HAR', 'Harina');
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'ALB', 'Albahaca');
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'TOM', 'Tomate');
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'ORE', 'Orégano');
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'LEV', 'Levadura');
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'AGU', 'Agua');
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'SAL', 'Sal');
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'HON', 'Hongos');
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'SCP', 'Salchichas de Pollo');
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'SCC', 'Salchichas de Carne');
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'JAC', 'Jamón de Carne');
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'ACE', 'Aceitunas');
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'BAC', 'Bacon');

COMMIT;


-- -----------------------------------------------------
-- Data for table `eif209_2001_p02`.`Recipe`
-- -----------------------------------------------------
START TRANSACTION;
USE `eif209_2001_p02`;
INSERT INTO `eif209_2001_p02`.`Recipe` (`idProduct`, `idIngredient`) VALUES (1, 1);
INSERT INTO `eif209_2001_p02`.`Recipe` (`idProduct`, `idIngredient`) VALUES (1, 3);
INSERT INTO `eif209_2001_p02`.`Recipe` (`idProduct`, `idIngredient`) VALUES (1, 6);
INSERT INTO `eif209_2001_p02`.`Recipe` (`idProduct`, `idIngredient`) VALUES (2, 3);
INSERT INTO `eif209_2001_p02`.`Recipe` (`idProduct`, `idIngredient`) VALUES (2, 6);
INSERT INTO `eif209_2001_p02`.`Recipe` (`idProduct`, `idIngredient`) VALUES (2, 14);
INSERT INTO `eif209_2001_p02`.`Recipe` (`idProduct`, `idIngredient`) VALUES (3, 1);
INSERT INTO `eif209_2001_p02`.`Recipe` (`idProduct`, `idIngredient`) VALUES (3, 3);
INSERT INTO `eif209_2001_p02`.`Recipe` (`idProduct`, `idIngredient`) VALUES (3, 5);
INSERT INTO `eif209_2001_p02`.`Recipe` (`idProduct`, `idIngredient`) VALUES (3, 6);
INSERT INTO `eif209_2001_p02`.`Recipe` (`idProduct`, `idIngredient`) VALUES (3, 7);
INSERT INTO `eif209_2001_p02`.`Recipe` (`idProduct`, `idIngredient`) VALUES (3, 11);
INSERT INTO `eif209_2001_p02`.`Recipe` (`idProduct`, `idIngredient`) VALUES (3, 12);
INSERT INTO `eif209_2001_p02`.`Recipe` (`idProduct`, `idIngredient`) VALUES (3, 13);
INSERT INTO `eif209_2001_p02`.`Recipe` (`idProduct`, `idIngredient`) VALUES (3, 15);

COMMIT;


-- -----------------------------------------------------
-- Data for table `eif209_2001_p02`.`Size`
-- -----------------------------------------------------
START TRANSACTION;
USE `eif209_2001_p02`;
INSERT INTO `eif209_2001_p02`.`Size` (`idSize`, `size`) VALUES (DEFAULT, 'Personal');
INSERT INTO `eif209_2001_p02`.`Size` (`idSize`, `size`) VALUES (DEFAULT, 'Grande');
INSERT INTO `eif209_2001_p02`.`Size` (`idSize`, `size`) VALUES (DEFAULT, 'Familiar');

COMMIT;


-- -----------------------------------------------------
-- Data for table `eif209_2001_p02`.`Inventory`
-- -----------------------------------------------------
START TRANSACTION;
USE `eif209_2001_p02`;
INSERT INTO `eif209_2001_p02`.`Inventory` (`idProduct`, `idSize`, `price`) VALUES (1, 1, 3500.50);
INSERT INTO `eif209_2001_p02`.`Inventory` (`idProduct`, `idSize`, `price`) VALUES (1, 2, 6723.22);
INSERT INTO `eif209_2001_p02`.`Inventory` (`idProduct`, `idSize`, `price`) VALUES (1, 3, 11000);
INSERT INTO `eif209_2001_p02`.`Inventory` (`idProduct`, `idSize`, `price`) VALUES (2, 1, 5000);
INSERT INTO `eif209_2001_p02`.`Inventory` (`idProduct`, `idSize`, `price`) VALUES (2, 2, 8000);
INSERT INTO `eif209_2001_p02`.`Inventory` (`idProduct`, `idSize`, `price`) VALUES (2, 3, 13000.55);
INSERT INTO `eif209_2001_p02`.`Inventory` (`idProduct`, `idSize`, `price`) VALUES (3, 1, 4500);
INSERT INTO `eif209_2001_p02`.`Inventory` (`idProduct`, `idSize`, `price`) VALUES (3, 2, 6000);
INSERT INTO `eif209_2001_p02`.`Inventory` (`idProduct`, `idSize`, `price`) VALUES (3, 3, 9000);

COMMIT;


-- -----------------------------------------------------
-- Data for table `eif209_2001_p02`.`Status`
-- -----------------------------------------------------
START TRANSACTION;
USE `eif209_2001_p02`;
INSERT INTO `eif209_2001_p02`.`Status` (`idStatus`, `description`) VALUES (DEFAULT, 'Se esta preparando la orden');
INSERT INTO `eif209_2001_p02`.`Status` (`idStatus`, `description`) VALUES (DEFAULT, 'La orden esta llegando a su destino');
INSERT INTO `eif209_2001_p02`.`Status` (`idStatus`, `description`) VALUES (DEFAULT, 'Se finalizo la orden');

COMMIT;


-- -----------------------------------------------------
-- Data for table `eif209_2001_p02`.`Order`
-- -----------------------------------------------------
START TRANSACTION;
USE `eif209_2001_p02`;
INSERT INTO `eif209_2001_p02`.`Order` (`idStatus`, `idInvoice`) VALUES (DEFAULT, 1);
INSERT INTO `eif209_2001_p02`.`Order` (`idStatus`, `idInvoice`) VALUES (DEFAULT, 2);

COMMIT;

