-- MySQL Script generated by MySQL Workbench
-- Sat Jun 13 19:00:49 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eif209_2001_p02
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `eif209_2001_p02` ;

-- -----------------------------------------------------
-- Schema eif209_2001_p02
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eif209_2001_p02` DEFAULT CHARACTER SET utf8 ;
USE `eif209_2001_p02` ;

-- -----------------------------------------------------
-- Table `eif209_2001_p02`.`Size`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p02`.`Size` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p02`.`Size` (
  `idSize` INT NOT NULL AUTO_INCREMENT,
  `size` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`idSize`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eif209_2001_p02`.`Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p02`.`Products` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p02`.`Products` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `idSize` INT NOT NULL,
  `code` VARCHAR(4) NULL,
  `description` VARCHAR(60) NULL,
  `price` DOUBLE NULL,
  PRIMARY KEY (`idProduct`, `idSize`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE,
  INDEX `fk_Products_Size1_idx` (`idSize` ASC) VISIBLE,
  CONSTRAINT `fk_Products_Size1`
    FOREIGN KEY (`idSize`)
    REFERENCES `eif209_2001_p02`.`Size` (`idSize`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eif209_2001_p02`.`Clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p02`.`Clients` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p02`.`Clients` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `idCard` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(8) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClient`),
  UNIQUE INDEX `idCard_UNIQUE` (`idCard` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eif209_2001_p02`.`Admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p02`.`Admins` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p02`.`Admins` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `idCard` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idAdmin`),
  UNIQUE INDEX `idCard_UNIQUE` (`idCard` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eif209_2001_p02`.`Clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p02`.`Clients` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p02`.`Clients` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `idCard` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(8) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClient`),
  UNIQUE INDEX `idCard_UNIQUE` (`idCard` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eif209_2001_p02`.`Status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p02`.`Status` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p02`.`Status` (
  `idStatus` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`idStatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eif209_2001_p02`.`Invoices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p02`.`Invoices` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p02`.`Invoices` (
  `idInvoice` INT NOT NULL AUTO_INCREMENT,
  `idStatus` INT NOT NULL,
  `idClient` INT NOT NULL,
  `date` TIMESTAMP NULL,
  PRIMARY KEY (`idInvoice`, `idStatus`),
  INDEX `fk_Invoices_Client1_idx` (`idClient` ASC) VISIBLE,
  INDEX `fk_Invoices_Status1_idx` (`idStatus` ASC) VISIBLE,
  CONSTRAINT `fk_Invoices_Client1`
    FOREIGN KEY (`idClient`)
    REFERENCES `eif209_2001_p02`.`Clients` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Invoices_Status1`
    FOREIGN KEY (`idStatus`)
    REFERENCES `eif209_2001_p02`.`Status` (`idStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eif209_2001_p02`.`Details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p02`.`Details` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p02`.`Details` (
  `idInvoice` INT NOT NULL,
  `idProduct` INT NOT NULL,
  `stock` INT NULL,
  PRIMARY KEY (`idInvoice`, `idProduct`),
  INDEX `fk_Details_Invoices1_idx` (`idInvoice` ASC) VISIBLE,
  INDEX `fk_Details_Products1_idx` (`idProduct` ASC) VISIBLE,
  CONSTRAINT `fk_Details_Invoices1`
    FOREIGN KEY (`idInvoice`)
    REFERENCES `eif209_2001_p02`.`Invoices` (`idInvoice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Details_Products1`
    FOREIGN KEY (`idProduct`)
    REFERENCES `eif209_2001_p02`.`Products` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eif209_2001_p02`.`Ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p02`.`Ingredients` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p02`.`Ingredients` (
  `idIngredient` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(3) NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idIngredient`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eif209_2001_p02`.`Feedbacks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p02`.`Feedbacks` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p02`.`Feedbacks` (
  `idFeedback` INT NOT NULL AUTO_INCREMENT,
  `idClient` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`idFeedback`),
  INDEX `fk_Feedbacks_Client1_idx` (`idClient` ASC) VISIBLE,
  CONSTRAINT `fk_Feedbacks_Client1`
    FOREIGN KEY (`idClient`)
    REFERENCES `eif209_2001_p02`.`Clients` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eif209_2001_p02`.`Recipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eif209_2001_p02`.`Recipe` ;

CREATE TABLE IF NOT EXISTS `eif209_2001_p02`.`Recipe` (
  `idProduct` INT NOT NULL,
  `idIngredient` INT NOT NULL,
  PRIMARY KEY (`idProduct`, `idIngredient`),
  INDEX `fk_Products_has_Ingredients_Ingredients1_idx` (`idIngredient` ASC) VISIBLE,
  INDEX `fk_Products_has_Ingredients_Products1_idx` (`idProduct` ASC) VISIBLE,
  CONSTRAINT `fk_Products_has_Ingredients_Products1`
    FOREIGN KEY (`idProduct`)
    REFERENCES `eif209_2001_p02`.`Products` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_has_Ingredients_Ingredients1`
    FOREIGN KEY (`idIngredient`)
    REFERENCES `eif209_2001_p02`.`Ingredients` (`idIngredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `eif209_2001_p02`;

DELIMITER $$

USE `eif209_2001_p02`$$
DROP TRIGGER IF EXISTS `eif209_2001_p02`.`Invoices_AFTER_INSERT` $$
USE `eif209_2001_p02`$$
CREATE DEFINER = CURRENT_USER TRIGGER `eif209_2001_p02`.`Invoices_AFTER_INSERT` AFTER INSERT ON `Invoices` FOR EACH ROW
BEGIN
	insert into `eif209_2001_p02`.order (idStatus, idInvoice) select 1, max(idInvoice) from `eif209_2001_p02`.invoices;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `eif209_2001_p02`.`Size`
-- -----------------------------------------------------
START TRANSACTION;
USE `eif209_2001_p02`;
INSERT INTO `eif209_2001_p02`.`Size` (`idSize`, `size`, `description`) VALUES (DEFAULT, 'Personal', 'Pizza');
INSERT INTO `eif209_2001_p02`.`Size` (`idSize`, `size`, `description`) VALUES (DEFAULT, 'Grande', 'Pizza');
INSERT INTO `eif209_2001_p02`.`Size` (`idSize`, `size`, `description`) VALUES (DEFAULT, 'Familiar', 'Pizza');
INSERT INTO `eif209_2001_p02`.`Size` (`idSize`, `size`, `description`) VALUES (DEFAULT, '500ML', 'Bebida');
INSERT INTO `eif209_2001_p02`.`Size` (`idSize`, `size`, `description`) VALUES (DEFAULT, '1L', 'Bebida');
INSERT INTO `eif209_2001_p02`.`Size` (`idSize`, `size`, `description`) VALUES (DEFAULT, '3L', 'Bebida');
INSERT INTO `eif209_2001_p02`.`Size` (`idSize`, `size`, `description`) VALUES (DEFAULT, 'Pequeno', 'Postres');
INSERT INTO `eif209_2001_p02`.`Size` (`idSize`, `size`, `description`) VALUES (DEFAULT, 'Grande', 'Postres');

COMMIT;


-- -----------------------------------------------------
-- Data for table `eif209_2001_p02`.`Products`
-- -----------------------------------------------------
START TRANSACTION;
USE `eif209_2001_p02`;
INSERT INTO `eif209_2001_p02`.`Products` (`idProduct`, `idSize`, `code`, `description`, `price`) VALUES (DEFAULT, 1, 'PEPP', 'Pizza de Peperronie', 4000);
INSERT INTO `eif209_2001_p02`.`Products` (`idProduct`, `idSize`, `code`, `description`, `price`) VALUES (DEFAULT, 1, 'JAQP', 'Pizza de Jamón y Queso', 4000);
INSERT INTO `eif209_2001_p02`.`Products` (`idProduct`, `idSize`, `code`, `description`, `price`) VALUES (DEFAULT, 1, 'SUPP', 'Pizza Suprema', 3000);
INSERT INTO `eif209_2001_p02`.`Products` (`idProduct`, `idSize`, `code`, `description`, `price`) VALUES (DEFAULT, 6, 'COCA', 'Coca Cola ', 2000);
INSERT INTO `eif209_2001_p02`.`Products` (`idProduct`, `idSize`, `code`, `description`, `price`) VALUES (DEFAULT, 6, 'FANN', 'Fanta Naranja', 1000);
INSERT INTO `eif209_2001_p02`.`Products` (`idProduct`, `idSize`, `code`, `description`, `price`) VALUES (DEFAULT, 7, 'PIEA', 'Pie de Arandanos', 3500);
INSERT INTO `eif209_2001_p02`.`Products` (`idProduct`, `idSize`, `code`, `description`, `price`) VALUES (DEFAULT, 7, 'TREL', 'Tres Leches', 5000);
COMMIT;


-- -----------------------------------------------------
-- Data for table `eif209_2001_p02`.`Admins`
-- -----------------------------------------------------
START TRANSACTION;
USE `eif209_2001_p02`;
INSERT INTO `eif209_2001_p02`.`Admins` (`idAdmin`, `idCard`, `name`, `lastname`, `password`) VALUES (DEFAULT, '504250570', 'Erick ', 'Badilla Gonzalez', '1234567b');
INSERT INTO `eif209_2001_p02`.`Admins` (`idAdmin`, `idCard`, `name`, `lastname`, `password`) VALUES (DEFAULT, '504250413', 'Carlos', 'Zhou Zheng', '1234567b');

COMMIT;


-- -----------------------------------------------------
-- Data for table `eif209_2001_p02`.`Clients`
-- -----------------------------------------------------
START TRANSACTION;
USE `eif209_2001_p02`;
INSERT INTO `eif209_2001_p02`.`Clients` (`idClient`, `idCard`, `name`, `lastname`, `address`, `phone`, `email`, `password`) VALUES (DEFAULT, '185045679', 'Ignacio', 'Monge Salazar', 'Montes de Oca Uruca', '60405010', 'nacho@gmail.com', 'qwer');
INSERT INTO `eif209_2001_p02`.`Clients` (`idClient`, `idCard`, `name`, `lastname`, `address`, `phone`, `email`, `password`) VALUES (DEFAULT, '150305402', 'Nicole ', 'Cannet Porras ', 'San Antonio de Belen ', '50501012', 'nicole@email.com', 'qwer');

COMMIT;


-- -----------------------------------------------------
-- Data for table `eif209_2001_p02`.`Status`
-- -----------------------------------------------------
START TRANSACTION;
USE `eif209_2001_p02`;
INSERT INTO `eif209_2001_p02`.`Status` (`idStatus`, `description`) VALUES (DEFAULT, 'Se esta preparando la orden');
INSERT INTO `eif209_2001_p02`.`Status` (`idStatus`, `description`) VALUES (DEFAULT, 'La orden esta llegando a su destino');
INSERT INTO `eif209_2001_p02`.`Status` (`idStatus`, `description`) VALUES (DEFAULT, 'Se finalizo la orden');

COMMIT;


-- -----------------------------------------------------
-- Data for table `eif209_2001_p02`.`Invoices`
-- -----------------------------------------------------
START TRANSACTION;
USE `eif209_2001_p02`;
INSERT INTO `eif209_2001_p02`.`Invoices` (`idInvoice`, `idStatus`, `idClient`, `date`) VALUES (DEFAULT, 1, 1, NULL);
INSERT INTO `eif209_2001_p02`.`Invoices` (`idInvoice`, `idStatus`, `idClient`, `date`) VALUES (DEFAULT, 1, 2, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `eif209_2001_p02`.`Details`
-- -----------------------------------------------------
START TRANSACTION;
USE `eif209_2001_p02`;
INSERT INTO `eif209_2001_p02`.`Details` (`idInvoice`, `idProduct`, `stock`) VALUES (1, 1, NULL);
INSERT INTO `eif209_2001_p02`.`Details` (`idInvoice`, `idProduct`, `stock`) VALUES (1, 2, NULL);
INSERT INTO `eif209_2001_p02`.`Details` (`idInvoice`, `idProduct`, `stock`) VALUES (1, 3, NULL);
INSERT INTO `eif209_2001_p02`.`Details` (`idInvoice`, `idProduct`, `stock`) VALUES (2, 1, NULL);
INSERT INTO `eif209_2001_p02`.`Details` (`idInvoice`, `idProduct`, `stock`) VALUES (2, 2, NULL);
INSERT INTO `eif209_2001_p02`.`Details` (`idInvoice`, `idProduct`, `stock`) VALUES (2, 3, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `eif209_2001_p02`.`Ingredients`
-- -----------------------------------------------------
START TRANSACTION;
USE `eif209_2001_p02`;
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'PEP', 'Pepperoni');
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'JAP', 'Jamón de Pollo');
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'QUM', 'Queso Mozzarella');
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'HAR', 'Harina');
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'ALB', 'Albahaca');
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'TOM', 'Tomate');
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'ORE', 'Orégano');
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'LEV', 'Levadura');
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'AGU', 'Agua');
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'SAL', 'Sal');
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'HON', 'Hongos');
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'SCP', 'Salchichas de Pollo');
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'SCC', 'Salchichas de Carne');
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'JAC', 'Jamón de Carne');
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'ACE', 'Aceitunas');
INSERT INTO `eif209_2001_p02`.`Ingredients` (`idIngredient`, `code`, `name`) VALUES (DEFAULT, 'BAC', 'Bacon');

COMMIT;


-- -----------------------------------------------------
-- Data for table `eif209_2001_p02`.`Recipe`
-- -----------------------------------------------------
START TRANSACTION;
USE `eif209_2001_p02`;
INSERT INTO `eif209_2001_p02`.`Recipe` (`idProduct`, `idIngredient`) VALUES (1, 1);
INSERT INTO `eif209_2001_p02`.`Recipe` (`idProduct`, `idIngredient`) VALUES (1, 3);
INSERT INTO `eif209_2001_p02`.`Recipe` (`idProduct`, `idIngredient`) VALUES (1, 6);
INSERT INTO `eif209_2001_p02`.`Recipe` (`idProduct`, `idIngredient`) VALUES (2, 3);
INSERT INTO `eif209_2001_p02`.`Recipe` (`idProduct`, `idIngredient`) VALUES (2, 6);
INSERT INTO `eif209_2001_p02`.`Recipe` (`idProduct`, `idIngredient`) VALUES (2, 14);
INSERT INTO `eif209_2001_p02`.`Recipe` (`idProduct`, `idIngredient`) VALUES (3, 1);
INSERT INTO `eif209_2001_p02`.`Recipe` (`idProduct`, `idIngredient`) VALUES (3, 3);
INSERT INTO `eif209_2001_p02`.`Recipe` (`idProduct`, `idIngredient`) VALUES (3, 5);
INSERT INTO `eif209_2001_p02`.`Recipe` (`idProduct`, `idIngredient`) VALUES (3, 6);
INSERT INTO `eif209_2001_p02`.`Recipe` (`idProduct`, `idIngredient`) VALUES (3, 7);
INSERT INTO `eif209_2001_p02`.`Recipe` (`idProduct`, `idIngredient`) VALUES (3, 11);
INSERT INTO `eif209_2001_p02`.`Recipe` (`idProduct`, `idIngredient`) VALUES (3, 12);
INSERT INTO `eif209_2001_p02`.`Recipe` (`idProduct`, `idIngredient`) VALUES (3, 13);
INSERT INTO `eif209_2001_p02`.`Recipe` (`idProduct`, `idIngredient`) VALUES (3, 15);

COMMIT;

